#!/bin/bash
set -ex
# generate configure
chmod +x bootstrap
test -e ./configure || ./bootstrap
chmod +x configure install-sh config.sub config.guess depcomp ltmain.sh
# configure once to set the version in build script
if [ -d /System/Library/Frameworks/PCSC.framework/Headers ]
then
    PCSC_CFLAGS="-I/System/Library/Frameworks/PCSC.framework/Headers"
    export PCSC_CFLAGS
else
    OSX_RELEASE=$@
    PCSC_CFLAGS="-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/PCSC.framework/Headers"
    export PCSC_CFLAGS
fi

make clean && make distclean
rm -fr configure install-sh config.sub config.guess
./bootstrap
./configure
# build and package installer
bash ./MacOSX/build-package $@
